### ISSUE TITLE
Alpha Home Page

### ISSUE THREAD

**Issue by robdrosenberg** [blitz-js/blitzjs.com#30]
This is a basic home page to help with the alpha release of Blitzjs

We want to display a little info on Blitz when you land on Blitzjs.com and some help links to getting started with the project.

- [x] Add Brandon's Blitz demo video
- [ ] Remove Features section on home page

- [ ] Mailing List form / link out to Original Mailchimp site

- [ ] Some initial Blitzjs Copy, Use below for inspiration / just use it lol

> Rails-like framework for monolithic, full-stack React apps.
> The central thesis is that most apps don’t need a REST or GraphQL API. Blitz brings back the simplicity of server rendered frameworks like Ruby on Rails while preserving everything we love about React.
> Additionally, Blitz is bringing other Rails goodness that’s missing in the React ecosystem like file structure and routing conventions, a really nice console REPL, intelligent code-scaffolding, and a fine-tuned out-of-the-box setup with Prettier, Typescript, ESlint, Jest, Cypress, etc.

**Add CTA buttons**
- [ ] Getting Started
- [ ] Help Build Blitz

**Comment by flybayer** [comment]
I've just updated the main repo README with content that'd be good for the website too.

**Comment by simonpeterdebbarma** [comment]
Is there anything I can help with here? @robdrosenberg

**Comment by robdrosenberg** [comment]
@simonpeterdebbarma It's being worked on in #47 @mgm1313 was working on the branch and made some good headway.
